title: Vijay Tadimeti
position: Project Instructor
affiliation: Oregon State University
email: tadimetv (at) oregonstate.edu
keywords: minimal academic
github_link: https://github.com/vijayvardhan94
linkedin: https://www.linkedin.com/in/vijaytadimeti
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
